### ISSUE TITLE
Workflow not accepting fastq

### ISSUE THREAD

**Issue by prenderj** [Arkarachai/STR-FM#19]
Hi

STR_FM looks very useful but unfortunately I am having a problem with the first step in the microsatellite_profiling galaxy workflow. When I provide "Step 1: Input dataset" with a single end fastq file I am getting the following error:

`Traceback (most recent call last):
  File "/mnt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/arkarachai-fungtammasan/str_fm/808bd6c3ac71/str_fm/microsatellite.py", line 1270, in <module>
    if __name__ == "__main__": main()
  File "/mnt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/arkarachai-fungtammasan/str_fm/808bd6c3ac71/str_fm/microsatellite.py", line 331, in main
    for seqInfo in sequence_reader(inputF):
  File "/mnt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/arkarachai-fungtammasan/str_fm/808bd6c3ac71/str_fm/microsatellite.py", line 1118, in fasta_sequences
    assert (False), "first sequence has no header"
AssertionError: first sequence has no header`

Checking microsatellite.py this error should only appear with fasta input not fastq:

``` python
def fasta_sequences(f):
seqName = None
seqNucs = None
for line in f:
line = line.strip()
if (line.startswith(">")):
if (seqName != None):
yield (seqName,"".join(seqNucs))
seqName = sequence_name(line)
seqNucs = []
elif (seqName == None):
assert (False), "first sequence has no header"
else:
seqNucs += [line]
if (seqName != None):
yield (seqName,"".join(seqNucs).upper().translate(nonDnaMap))
```

And if I actually give it a fasta file as input it runs ok. So appears although asking for a fastq file it is testing for a fasta file and therefore crashing? Or am I making a mistake?

Thanks a lot
James

**Comment by Arkarachai** [comment]
Dear James,

I see. You are 100% correct. I appear that the default option in work flow for microsatellite profiling is "fasta" not "fastq". I probably forgot to click this when I update the toolshed path last week. The quickest way to fix this is to select "fastq" as input in your downloaded version. However, I will fix this permanently by updating the online workflow. I will notify you once it has been updated.
Thank you so much for notifying this.
Best,
Chai

**Comment by Arkarachai** [comment]
Dear James,

It has been fixed. You may update or download the new version. I personally recommend you to uninstall both str_fm, suite_str_fm_1_0 and related workflow. Then reinstall the suite_str_fm_1_0 and the workflows from str_fm. With update, sometimes I got duplicated tools.
However, if you have already build the special pipeline from the old version, you may just change the parameter in "STR detection" step of "microsatellite_prifling(both normal and v2)" from "fasta" to "fastq". That's all I did. I just update the whole thing to prevent other people to face the same problem.
If you have any issues, don't hesitate to let me know. Thanks again for reporting this.

Best,
Chai

**Comment by prenderj** [comment]
Hi Chai

Thanks a lot. That seems to be working now.

I was wondering if I can also ask is there anywhere that describes the columns in the final genotype file from the workflow? Some of them are obvious but be good to check.

Thanks a lot
James

**Comment by Arkarachai** [comment]
Hi James,

The workflow itself does not have description of column. However, if you click on each individual tool that you installed and scroll down, you can see the column description under "What it does" I think I wrote down for all tools that I developed.
For example, for genotype file, the input and output description are as follow:
Input

The input files need to contain at least three columns.
Column 1 = location of STR locus.
Column 2 = length profile (length of STR in each read that mapped to this location in comma separated format).
Column 3 = motif of STR in this locus. The input file can contain more than three columns.
Output

The output will be contain original three (or more) columns as the input. However, it will also have these following columns.

Additional column 1 = homozygote/heterozygote label.
Additional column 2 = log based 10 of (the probability of homozygote/the probability of heterozygote)
Additional column 3 = Allele for most probable homozygote.
Additional column 4 = Allele 1 for most probable heterozygote.
Additional column 5 = Allele 2 for most probable heterozygote.

The Additional column 1 label loci as homozygote/heterozygote by just which one is more likely. However, sometimes, the difference is subtle. You may use Additional column 2 to adjust your cut off to report genotype.

**Comment by prenderj** [comment]
Hi Chai

Thats great. Thanks for the help

James
