### ISSUE TITLE
error-rates-files

### ISSUE THREAD

**Issue by michaeldonaldson** [Arkarachai/STR-FM#20]
Dear Arkarachai, 

I am trying to run through a workflow in galaxy and cannot find the input dataset for step 3. How can I find the error-rates-file? I think the link "https://usegalaxy.org/u/guru%40psu.edu/h/error-rates-files" is broken.

Thank you for your help, 
Mike

**Comment by Arkarachai** [comment]
Thank you Mike for reporting this to us. I will get in touch with Galaxy team right away and get back to you shortly.

**Comment by Arkarachai** [comment]
Hi Mark,

It should work now. Thank you for reporting this.

Best,
Chai
