### ISSUE TITLE
An issue with 'Fetch bases flanking'

### ISSUE THREAD

**Issue by Bogi-T** [Arkarachai/STR-FM#21]
Hello Arkarachai,

I tried using microsatellite_profiling_v2 workflow that utilizes STR-FM tools for my Master's project, but I get an error mid-way through. I imported workflow files to my Galaxy main account. The tool 'Fetch bases flanking' gives this error:

Traceback (most recent call last): File "/galaxy/main/shed_tools/toolshed.g2.bx.psu.edu/repos/arkarachai-fungtammasan/str_fm/48b5f719e36a/str_fm/pair_fetch_DNA_ff.py", line 14, in <module> from galaxy import eggs ImportError: No module named galaxy

I checked your GitHub account and found that you've changed your 'pair_fetch_DNA_ff.py' script 7 days ago, but when I looked at the repository it turns out that the last change was made a year ago. So, if I'm not wrong, changes in the python script are not in 'Fetch bases flanking' tool that I'm trying to use.

This is not a big issue for me (I'll run it in the command line on my installed Galaxy), but I just wanted to report this error in case you were unaware of it.

Sincerely,
Bogi

MEME Master student at ISEM
University of Montpellier 2
France

**Comment by Arkarachai** [comment]
Hi Bogi,

Thank you for reporting this to me. I appreciate very much. Only the Galaxy
team has access to the regression test, so I would not know that it fail
unless they notify me.
By random chance, I found a person run into this problem in a webboard a
week ago. After an investigation, the module galaxy is no longer accessible
by the recent update. This module was put in my code for a historical
reason, so removing it should solve the issue. Have you had a chance to try
this new code? Hopefully, it works for you. Note that that tool Combine
mapped faux paired-end reads is updated for the same reason as well.
Also, when you mentioned that the code in repo was changed a year ago. What
repo do you refer to?
I am contacting Galaxy team to change the underline code, but this would
take a few week. Thank you for reporting this to me.

Best,
Chai

**Comment by Bogi-T** [comment]
Hello Chai,

Thanks for the prompt response.  Yes, the new code works, but I had an issue when I just imported 'profiling_microsatellites_v2.ga' to my Galaxy main account from my installed Galaxy. Regarding the repo, I was referring to 20dc70f85ff7 pushed on 2016-07-24. I assumed that any change made since wouldn't be included in the tool. It's really not a big problem; I'll just use modified versions of your PBS scripts on our Galaxy server.

Best,
Bogi

**Comment by Arkarachai** [comment]
Hi Bogi,

Thank you for catching this. All the workflows that use these two tools
will need to be updated as well. Once the tool update is done, I will make
sure all related workflow are updated.
I sent a message to Galaxy's custodian. Hopefully, he will get back to me
soon.

Best,
Chai

**Comment by Arkarachai** [comment]
Hi Bogi,

I got a response from Galaxy team today. It turns out to be their security upgrade that hides such library. They will whitelist my tools, so people can continue using it. 
Note that the new version of code (in this github) is better (cleaner). Soon, I will update my tool in galaxy toolshed as well.

Best,
Chai

**Comment by Bogi-T** [comment]
Hello Chai,

That's a great news! Thanks for handling this so quickly!

Best,
Bogi
