### ISSUE TITLE
microsatellite.py on reference genome only reports the last chromosome

### ISSUE THREAD

**Issue by danielecook** [Arkarachai/STR-FM#24]
When I run the following, I only get the last chromosome when doing reference profiling:

```
python microsatellite.py ${REFERENCE} --fasta --period=2 --partialmotifs --minlength=4 --prefix=0 --suffix=0 --hamming=0 --multipleruns --flankdisplay=0  --splitbyvalidity
```

**Comment by Arkarachai** [comment]
Hi Daniel,
I can't reproduce that. See example below

$ less chromosome.fasta
>1
AGCATGACGATGCAGAGCAGCAGATATATATATATAGCAGACAGACAGTAGCA
AGCATGACGATGCAGAGCAGCAGATATATATATATAGCAGACAGACAGTAGCA
>2
AGCATGACGATGCAGAGCAGCAGATATATATATATAGCAGACAGACAGTAGCA
AGCATGACGATGCAGAGCAGCAGATATATATATATACAGACACACAGCAGACAGACAGTAGCA

$ python microsatellite.py chromosome.fasta --fasta --period=2 --partialmotifs --minlength=4 --prefix=0 --suffix=0 --hamming=0 --multipleruns --flankdisplay=0  --splitbyvalidity
4	13	89	AG	0	1	agag	.
13	23	70	AT	0	1	atatatatatata	.
4	66	36	AG	0	1	agag	.
13	76	17	AT	0	1	atatatatatata	.
4	13	99	AG	0	2	agag	.
13	23	80	AT	0	2	atatatatatata	.
4	66	46	AG	0	2	agag	.
13	76	27	AT	0	2	atatatatatata	.
7	92	17	AC	0	2	acacaca	.

I got data from all chromosomes just fine.
Could you check the fasta name or the space between input?

**Comment by danielecook** [comment]
Are you using a Mac windows or Linux?

**Comment by Arkarachai** [comment]
I'm on Mac. I have tried on Unix, but not window.

**Comment by Arkarachai** [comment]
Hi Daniel,
Since I cannot reproduce your error and did not see more development on this issue, I assume that you have figured it out. Hopefully, you got a workable solution.
